### ISSUE TITLE
Don't follow HTTP redirects

### ISSUE THREAD

**Issue by 21plus2** [jamesseanwright/valimate#1]
Thanks for the great tool!

It works fine, but if the server returns a 302 the tool don't follow them and validate the markup of the redirect.
So you get a wrong error :(

I find a solution http://syskall.com/how-to-follow-http-redirects-in-node-dot-js/.
After install 'follow-redirects' and change the first 2 line in /valimate/lib/services/httpService.js to:

const http = require('follow-redirects').http;
const https = require('follow-redirects').https;

your tool works fine :)

regards 21plus2

**Comment by jamesseanwright** [comment]
Hey 21plus2,

Sorry for the late reply, I didn't get any kind of notification for this issue!

I'll take a look next week and release a patched version. :)

Cheers
James

**Comment by jamesseanwright** [comment]
Hey 21plus2,

This is now fixed as of version 2.0.2!

The reason for the major version bump is that the contract for the local server configuration (`localAppServer` in valimate.json) has changed to satisfy [#2](https://github.com/jamesseanwright/valimate/issues/2). I would have released this as a patch initially, but the breaking change is tiny. Consult the README for more information.

Commit [5b44cb4e99a82d7acf33383444f17c4b687aa91c](https://github.com/jamesseanwright/valimate/commit/5b44cb4e99a82d7acf33383444f17c4b687aa91c) details my changes and the tests written to verify the functionality. I know that I had locked down the version of `request` in my package.json file, but this is fixed in the version number specified above

I'll close this issue, but please comment and reopen if it isn't working for you.

Cheers,
James
