### ISSUE TITLE
Escape validate on customer attribute of tags

### ISSUE THREAD

**Issue by Nguonchhay** [jamesseanwright/valimate#9]
I integrate the facebook like button. That plugin add extra attribute `fb:like:layout` in tag `a`. As the result, the `valimate` displays:
- Error: 
`Attribute “fb:like:layout” not allowed on element “a” at this point. - Line 14, Column 9038`
- Warning:
`Attribute “fb:like:layout” is not serializable as XML 1.0.`

**Comment by jamesseanwright** [comment]
Hi,

I've just attempted to emulate this by directly submitting the following markup to [W3's Nu checker instance](https://validator.w3.org/nu/#textarea):

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Test</title>
    </head>
    <body>
        <h1>Test</h1>

        <div class="addthis_toolbox addthis_default_style ">
            <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        </div>
    </body>
</html>
```

This results in the error you've mentioned, but this is because `fb:like:layout` is not a valid attribute for `<a>` elements. Therefore, this is not an issue with Valimate. If possible, you should use an alternative plugin that generates valid markup.
